Fix issue when enable_mem_cache = False
\script.module.simplecache\lib\simplecache.py",  line 63, in get
 if result is None:
UnboundLocalError: local variable 'result' referenced before assignment